//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Compiler.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutProgramItemHeader {
            get {
                return ResourceManager.GetString("AboutProgramItemHeader", resourceCulture);
            }
        }
        
        public static string AboutProgramItemHeaderDescription {
            get {
                return ResourceManager.GetString("AboutProgramItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string AnalysisMethodMenuItemHeader {
            get {
                return ResourceManager.GetString("AnalysisMethodMenuItemHeader", resourceCulture);
            }
        }
        
        public static string BibliographyMenuItemHeader {
            get {
                return ResourceManager.GetString("BibliographyMenuItemHeader", resourceCulture);
            }
        }
        
        public static string CallDocsItemHeader {
            get {
                return ResourceManager.GetString("CallDocsItemHeader", resourceCulture);
            }
        }
        
        public static string CallDocsItemHeaderDescription {
            get {
                return ResourceManager.GetString("CallDocsItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string CopyMenuItemHeader {
            get {
                return ResourceManager.GetString("CopyMenuItemHeader", resourceCulture);
            }
        }
        
        public static string CopyMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("CopyMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string CreateMenuItemHeader {
            get {
                return ResourceManager.GetString("CreateMenuItemHeader", resourceCulture);
            }
        }
        
        public static string CreateMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("CreateMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string CutMenuItemHeader {
            get {
                return ResourceManager.GetString("CutMenuItemHeader", resourceCulture);
            }
        }
        
        public static string CutMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("CutMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string DecreaseTextSizeMenuItemHeader {
            get {
                return ResourceManager.GetString("DecreaseTextSizeMenuItemHeader", resourceCulture);
            }
        }
        
        public static string DeleteMenuItemHeader {
            get {
                return ResourceManager.GetString("DeleteMenuItemHeader", resourceCulture);
            }
        }
        
        public static string DeleteMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("DeleteMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string DiagnosticNeutralizationMenuItemHeader {
            get {
                return ResourceManager.GetString("DiagnosticNeutralizationMenuItemHeader", resourceCulture);
            }
        }
        
        public static string DocsItemHeader {
            get {
                return ResourceManager.GetString("DocsItemHeader", resourceCulture);
            }
        }
        
        public static string DocsWindowTitle {
            get {
                return ResourceManager.GetString("DocsWindowTitle", resourceCulture);
            }
        }
        
        public static string EditMenuItemHeader {
            get {
                return ResourceManager.GetString("EditMenuItemHeader", resourceCulture);
            }
        }
        
        public static string ExitMenuItemHeader {
            get {
                return ResourceManager.GetString("ExitMenuItemHeader", resourceCulture);
            }
        }
        
        public static string ExitMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("ExitMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string FileMenuItemHeader {
            get {
                return ResourceManager.GetString("FileMenuItemHeader", resourceCulture);
            }
        }
        
        public static string GrammarClassificationMenuItemHeader {
            get {
                return ResourceManager.GetString("GrammarClassificationMenuItemHeader", resourceCulture);
            }
        }
        
        public static string GrammarMenuItemHeader {
            get {
                return ResourceManager.GetString("GrammarMenuItemHeader", resourceCulture);
            }
        }
        
        public static string IncreaseTextSizeMenuItemHeader {
            get {
                return ResourceManager.GetString("IncreaseTextSizeMenuItemHeader", resourceCulture);
            }
        }
        
        public static string OpenMenuItemHeader {
            get {
                return ResourceManager.GetString("OpenMenuItemHeader", resourceCulture);
            }
        }
        
        public static string OpenMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("OpenMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string PasteMenuItemHeader {
            get {
                return ResourceManager.GetString("PasteMenuItemHeader", resourceCulture);
            }
        }
        
        public static string PasteMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("PasteMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string ProblemFormulationMenuItemHeader {
            get {
                return ResourceManager.GetString("ProblemFormulationMenuItemHeader", resourceCulture);
            }
        }
        
        public static string RedoMenuItemHeader {
            get {
                return ResourceManager.GetString("RedoMenuItemHeader", resourceCulture);
            }
        }
        
        public static string RedoMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("RedoMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string RunMenuItemHeader {
            get {
                return ResourceManager.GetString("RunMenuItemHeader", resourceCulture);
            }
        }
        
        public static string FixMenuItemHeader {
            get {
                return ResourceManager.GetString("FixMenuItemHeader", resourceCulture);
            }
        }
        
        public static string SaveAsMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveAsMenuItemHeader", resourceCulture);
            }
        }
        
        public static string SaveAsMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("SaveAsMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string SaveMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveMenuItemHeader", resourceCulture);
            }
        }
        
        public static string SaveMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("SaveMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string SelectAllMenuItemHeader {
            get {
                return ResourceManager.GetString("SelectAllMenuItemHeader", resourceCulture);
            }
        }
        
        public static string SelectAllMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("SelectAllMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string SourceCodeMenuItemHeader {
            get {
                return ResourceManager.GetString("SourceCodeMenuItemHeader", resourceCulture);
            }
        }
        
        public static string TextExampleMenuItemHeader {
            get {
                return ResourceManager.GetString("TextExampleMenuItemHeader", resourceCulture);
            }
        }
        
        public static string TextMenuItemHeader {
            get {
                return ResourceManager.GetString("TextMenuItemHeader", resourceCulture);
            }
        }
        
        public static string TextSizeMenuItemHeader {
            get {
                return ResourceManager.GetString("TextSizeMenuItemHeader", resourceCulture);
            }
        }
        
        public static string UndoMenuItemHeader {
            get {
                return ResourceManager.GetString("UndoMenuItemHeader", resourceCulture);
            }
        }
        
        public static string UndoMenuItemHeaderDescription {
            get {
                return ResourceManager.GetString("UndoMenuItemHeaderDescription", resourceCulture);
            }
        }
        
        public static string ToolbarCreate {
            get {
                return ResourceManager.GetString("ToolbarCreate", resourceCulture);
            }
        }
        
        public static string ToolbarOpen {
            get {
                return ResourceManager.GetString("ToolbarOpen", resourceCulture);
            }
        }
        
        public static string ToolbarSave {
            get {
                return ResourceManager.GetString("ToolbarSave", resourceCulture);
            }
        }
        
        public static string ToolbarUndo {
            get {
                return ResourceManager.GetString("ToolbarUndo", resourceCulture);
            }
        }
        
        public static string ToolbarRedo {
            get {
                return ResourceManager.GetString("ToolbarRedo", resourceCulture);
            }
        }
        
        public static string ToolbarCopy {
            get {
                return ResourceManager.GetString("ToolbarCopy", resourceCulture);
            }
        }
        
        public static string ToolbarCut {
            get {
                return ResourceManager.GetString("ToolbarCut", resourceCulture);
            }
        }
        
        public static string ToolbarPaste {
            get {
                return ResourceManager.GetString("ToolbarPaste", resourceCulture);
            }
        }
        
        public static string ToolbarRun {
            get {
                return ResourceManager.GetString("ToolbarRun", resourceCulture);
            }
        }
        
        public static string ToolbarFix {
            get {
                return ResourceManager.GetString("ToolbarFix", resourceCulture);
            }
        }
        
        public static string ToolbarCallDocs {
            get {
                return ResourceManager.GetString("ToolbarCallDocs", resourceCulture);
            }
        }
        
        public static string ToolbarAboutProgram {
            get {
                return ResourceManager.GetString("ToolbarAboutProgram", resourceCulture);
            }
        }
        
        public static string SaveDialogDontSave {
            get {
                return ResourceManager.GetString("SaveDialogDontSave", resourceCulture);
            }
        }
        
        public static string SaveDialogCancel {
            get {
                return ResourceManager.GetString("SaveDialogCancel", resourceCulture);
            }
        }
        
        public static string SaveDialogSave {
            get {
                return ResourceManager.GetString("SaveDialogSave", resourceCulture);
            }
        }
        
        public static string SaveDialogContentHeader {
            get {
                return ResourceManager.GetString("SaveDialogContentHeader", resourceCulture);
            }
        }
        
        public static string SaveDialogSupportingText {
            get {
                return ResourceManager.GetString("SaveDialogSupportingText", resourceCulture);
            }
        }
        
        public static string WindowWarningTitle {
            get {
                return ResourceManager.GetString("WindowWarningTitle", resourceCulture);
            }
        }
        
        public static string SaveFilePickerTitle {
            get {
                return ResourceManager.GetString("SaveFilePickerTitle", resourceCulture);
            }
        }
        
        public static string UntitledFileName {
            get {
                return ResourceManager.GetString("UntitledFileName", resourceCulture);
            }
        }
        
        public static string TokensTab {
            get {
                return ResourceManager.GetString("TokensTab", resourceCulture);
            }
        }
        
        public static string TokensCodeColumn {
            get {
                return ResourceManager.GetString("TokensCodeColumn", resourceCulture);
            }
        }
        
        public static string TokensTypeColumn {
            get {
                return ResourceManager.GetString("TokensTypeColumn", resourceCulture);
            }
        }
        
        public static string TokensTokenColumn {
            get {
                return ResourceManager.GetString("TokensTokenColumn", resourceCulture);
            }
        }
        
        public static string ErrorsTab {
            get {
                return ResourceManager.GetString("ErrorsTab", resourceCulture);
            }
        }
        
        public static string ErrorsPositionColumn {
            get {
                return ResourceManager.GetString("ErrorsPositionColumn", resourceCulture);
            }
        }
        
        public static string TokensPositionColumn {
            get {
                return ResourceManager.GetString("TokensPositionColumn", resourceCulture);
            }
        }
        
        public static string ErrorsDescriptionColumn {
            get {
                return ResourceManager.GetString("ErrorsDescriptionColumn", resourceCulture);
            }
        }
        
        public static string TokenTypeConstKeyword {
            get {
                return ResourceManager.GetString("TokenTypeConstKeyword", resourceCulture);
            }
        }
        
        public static string TokenTypeIdentifier {
            get {
                return ResourceManager.GetString("TokenTypeIdentifier", resourceCulture);
            }
        }
        
        public static string TokenTypeColon {
            get {
                return ResourceManager.GetString("TokenTypeColon", resourceCulture);
            }
        }
        
        public static string TokenTypeAmpersand {
            get {
                return ResourceManager.GetString("TokenTypeAmpersand", resourceCulture);
            }
        }
        
        public static string TokenTypeStrKeyword {
            get {
                return ResourceManager.GetString("TokenTypeStrKeyword", resourceCulture);
            }
        }
        
        public static string TokenTypeAssignmentOperator {
            get {
                return ResourceManager.GetString("TokenTypeAssignmentOperator", resourceCulture);
            }
        }
        
        public static string TokenTypeStringLiteral {
            get {
                return ResourceManager.GetString("TokenTypeStringLiteral", resourceCulture);
            }
        }
        
        public static string TokenTypeOperatorEnd {
            get {
                return ResourceManager.GetString("TokenTypeOperatorEnd", resourceCulture);
            }
        }
        
        public static string TokenTypeSeparator {
            get {
                return ResourceManager.GetString("TokenTypeSeparator", resourceCulture);
            }
        }
        
        public static string TokenErrorUnexpectedSymbol {
            get {
                return ResourceManager.GetString("TokenErrorUnexpectedSymbol", resourceCulture);
            }
        }
        
        public static string TokenErrorUnterminatedString {
            get {
                return ResourceManager.GetString("TokenErrorUnterminatedString", resourceCulture);
            }
        }
        
        public static string TokenErrorIdentifierCanOnlyStartWithALetter {
            get {
                return ResourceManager.GetString("TokenErrorIdentifierCanOnlyStartWithALetter", resourceCulture);
            }
        }
        
        public static string ConstKeywordExpected {
            get {
                return ResourceManager.GetString("ConstKeywordExpected", resourceCulture);
            }
        }
        
        public static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        public static string TypeDividerExpected {
            get {
                return ResourceManager.GetString("TypeDividerExpected", resourceCulture);
            }
        }
        
        public static string LinkExpected {
            get {
                return ResourceManager.GetString("LinkExpected", resourceCulture);
            }
        }
        
        public static string StrTypeExpected {
            get {
                return ResourceManager.GetString("StrTypeExpected", resourceCulture);
            }
        }
        
        public static string AssignmentOperatorExpected {
            get {
                return ResourceManager.GetString("AssignmentOperatorExpected", resourceCulture);
            }
        }
        
        public static string StringLiteralExpected {
            get {
                return ResourceManager.GetString("StringLiteralExpected", resourceCulture);
            }
        }
        
        public static string OperatorEndExpected {
            get {
                return ResourceManager.GetString("OperatorEndExpected", resourceCulture);
            }
        }
        
        public static string NothingExpected {
            get {
                return ResourceManager.GetString("NothingExpected", resourceCulture);
            }
        }
        
        public static string SeparatorExpected {
            get {
                return ResourceManager.GetString("SeparatorExpected", resourceCulture);
            }
        }
        
        public static string ParseErrorsTab {
            get {
                return ResourceManager.GetString("ParseErrorsTab", resourceCulture);
            }
        }
    }
}
